{"status":"OK","subtests":[{"name":"Reaction must run even after the exception is thrown","status":"PASS"}]}