{"status":"TIMEOUT","subtests":[{"name":"global setup","status":"PASS"},{"name":"FetchEvent.handled should resolve when respondWith() is not called for a navigation request","status":"TIMEOUT"},{"name":"FetchEvent.handled should resolve when respondWith() is not called for a sub-resource request","status":"NOTRUN"},{"name":"FetchEvent.handled should reject when respondWith() is not called and the event is canceled","status":"NOTRUN"},{"name":"FetchEvent.handled should resolve when the promise provided to respondWith() is resolved","status":"NOTRUN"},{"name":"FetchEvent.handled should reject when the promise provided to respondWith() is resolved to an invalid response","status":"NOTRUN"},{"name":"FetchEvent.handled should reject when the promise provided to respondWith() is rejected","status":"NOTRUN"},{"name":"global cleanup","status":"NOTRUN"}]}