{"status":"OK","subtests":[{"name":"Calling observe() with entryTypes and then type should throw an InvalidModificationError","status":"FAIL"},{"name":"Calling observe() with type and then entryTypes should throw an InvalidModificationError","status":"FAIL"},{"name":"Calling observe() with type and entryTypes should throw a SyntaxError","status":"FAIL"},{"name":"Passing in unknown values to type does throw an exception.","status":"FAIL"},{"name":"observe() with different type values stacks.","status":"FAIL"}]}