{"status":"TIMEOUT","subtests":[{"name":"Test pausing then playing does not change the finished promise","status":"TIMEOUT"},{"name":"Test restarting a finished animation","status":"NOTRUN"},{"name":"Test restarting a reversed finished animation","status":"NOTRUN"},{"name":"Test redundant finishing of animation","status":"NOTRUN"},{"name":"Finished promise does not resolve when paused","status":"NOTRUN"},{"name":"Finished promise does not resolve when pause-pending","status":"NOTRUN"},{"name":"The finished promise is fulfilled with its Animation","status":"NOTRUN"},{"name":"finished promise is rejected when an animation is canceled by calling cancel()","status":"NOTRUN"},{"name":"canceling an already-finished animation replaces the finished promise","status":"NOTRUN"},{"name":"Test finished promise changes for animation duration changes","status":"NOTRUN"},{"name":"Test finished promise changes when playbackRate == 0","status":"NOTRUN"},{"name":"Test finished promise resolves when reaching to the natural boundary.","status":"NOTRUN"},{"name":"Test finished promise changes when a prior finished promise resolved and the animation falls out finished state","status":"NOTRUN"},{"name":"Test no new finished promise generated when finished state is checked asynchronously","status":"PASS"},{"name":"Test new finished promise generated when finished state is checked synchronously","status":"PASS"},{"name":"Test synchronous finished promise resolved even if finished state is changed soon","status":"NOTRUN"},{"name":"Test synchronous finished promise resolved even if asynchronous finished promise happens just before synchronous promise","status":"NOTRUN"},{"name":"Test finished promise is not resolved when the animation falls out finished state immediately","status":"NOTRUN"},{"name":"Test finished promise is not resolved once the animation falls out finished state even though the current finished promise is generated soon after animation state became finished","status":"NOTRUN"},{"name":"Finished promise should be resolved after the ready promise is resolved","status":"NOTRUN"},{"name":"Finished promise should be rejected after the ready promise is rejected","status":"NOTRUN"},{"name":"Finished promise does not report an unhandledrejection when rejected","status":"NOTRUN"}]}