{"status":"OK","subtests":[{"name":"# AUDIT TASK RUNNER STARTED.","status":"PASS"},{"name":"Executing \"test-suspend\"","status":"FAIL"},{"name":"Executing \"test-resume\"","status":"FAIL"},{"name":"Executing \"test-after-close\"","status":"FAIL"},{"name":"Executing \"resume-running-context\"","status":"FAIL"},{"name":"Audit report","status":"PASS"},{"name":"> [test-suspend] Test suspend() for offline context","status":"PASS"},{"name":"X offlineContext = new OfflineAudioContext(1, 44100, 44100) incorrectly threw ReferenceError: \"OfflineAudioContext is not defined\".","status":"FAIL"},{"name":"> [test-resume] Test resume() for offline context","status":"PASS"},{"name":"X p2 = offlineContext.resume() incorrectly threw TypeError: \"offlineContext is undefined\".","status":"FAIL"},{"name":"X p2 instanceof Promise is not true. Got false.","status":"FAIL"},{"name":"> [test-after-close] Test state after context closed","status":"PASS"},{"name":"> [resume-running-context] Test resuming a running context","status":"PASS"},{"name":"X Create online context incorrectly threw ReferenceError: \"AudioContext is not defined\".","status":"FAIL"},{"name":"# AUDIT TASK RUNNER FINISHED: 3 out of 4 tasks were failed.","status":"FAIL"}]}