{"status":"ERROR","subtests":[{"name":"Response reader read() promise should reject after a network error happening after resolving fetch promise","status":"PASS"}]}