{"status":"ERROR","subtests":[{"name":"navigate() and respondWith with a reject promise","status":"FAIL"}]}