{"status":"OK","subtests":[{"name":"# AUDIT TASK RUNNER STARTED.","status":"PASS"},{"name":"Executing \"setup\"","status":"PASS"},{"name":"Executing \"Test 1\"","status":"PASS"},{"name":"Executing \"Test 2\"","status":"PASS"},{"name":"Executing \"Test 3\"","status":"PASS"},{"name":"Executing \"Test 4\"","status":"PASS"},{"name":"Audit report","status":"PASS"},{"name":"> [setup] Contexts for testing","status":"PASS"},{"name":"  c1 = new AudioContext() did not throw an exception.","status":"PASS"},{"name":"  c2 = new AudioContext() did not throw an exception.","status":"PASS"},{"name":"< [setup] All assertions passed. (total 2 assertions)","status":"PASS"},{"name":"> [Test 1] Connect nodes between contexts","status":"PASS"},{"name":"  Test 1: g1 = new GainNode(c1) did not throw an exception.","status":"PASS"},{"name":"  Test 1: g2 = new GainNode(c2) did not throw an exception.","status":"PASS"},{"name":"X Test 1: g2.connect(g1) threw \"SyntaxError\" instead of InvalidAccessError.","status":"FAIL"},{"name":"< [Test 1] 1 out of 3 assertions were failed.","status":"FAIL"},{"name":"> [Test 2] Connect AudioParam between contexts","status":"PASS"},{"name":"  Test 2: g1 = new GainNode(c1) did not throw an exception.","status":"PASS"},{"name":"  Test 2: g2 = new GainNode(c2) did not throw an exception.","status":"PASS"},{"name":"X Test 2: g2.connect(g1.gain) threw \"SyntaxError\" instead of InvalidAccessError.","status":"FAIL"},{"name":"< [Test 2] 1 out of 3 assertions were failed.","status":"FAIL"},{"name":"> [Test 3] Disconnect nodes between contexts","status":"PASS"},{"name":"  Test 3: g1 = new GainNode(c1) did not throw an exception.","status":"PASS"},{"name":"  Test 3: g2 = new GainNode(c2) did not throw an exception.","status":"PASS"},{"name":"  Test 3: g2.disconnect(g1) threw InvalidAccessError: \"The given destination is not connected\".","status":"PASS"},{"name":"< [Test 3] All assertions passed. (total 3 assertions)","status":"PASS"},{"name":"> [Test 4] Disconnect AudioParam between contexts","status":"PASS"},{"name":"  Test 4: g1 = new GainNode(c1) did not throw an exception.","status":"PASS"},{"name":"  Test 4: g2 = new GainNode(c2) did not throw an exception.","status":"PASS"},{"name":"  Test 4: g2.connect(g1.gain) threw InvalidAccessError: \"The given destination is not connected\".","status":"PASS"},{"name":"< [Test 4] All assertions passed. (total 3 assertions)","status":"PASS"},{"name":"# AUDIT TASK RUNNER FINISHED: 2 out of 5 tasks were failed.","status":"FAIL"}]}