{"status":"OK","subtests":[{"name":"synchronously after abort() is called","status":"FAIL"},{"name":"in a promise microtask after abort() is called, before the transaction abort event is fired","status":"FAIL"},{"name":"in the abort event handler for a transaction aborted due to an abort() call","status":"FAIL"},{"name":"in a setTimeout(0) callback after the abort event is fired for a transaction aborted due to an abort() call","status":"FAIL"}]}