{"status":"OK","subtests":[{"name":"The open promise should reject with a TypeError when quota is requested outside the range of 1 to Number.MAX_SAFE_INTEGER.","status":"PASS"},{"name":"A QuotaExceededError is thrown when a storage API exceeds the quota of the bucket its in.","status":"PASS"}]}